ТЗ13. Разработка нового приложения. Добавлен функционал поиска вещи.
VladislavKubarev/java-shareit pull request #1
Opened 2023-07-21 12:25 UTC by VladislavKubarev

2023-07-22 09:54 UTC, alexache requested changes

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") long userId, @Valid @RequestBody Item item) {
Почему на вход приходит модель, а не ДТО? ДТО классы для использования в контроллере, взаимодействия с "клиентом", а модель только для хранения данных

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank(message = "Имя не может быть пустым!")
На модели нет смысла в валидациях

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
Сторадж не должен зависеть от других стораджей или работать с маппером - это больше для сервиса

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private long userId;
Что такое userId? то же что и owner? Почему owner строка, а не объект User?

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public ItemDto createItem(long userId, Item item) {
Сторадж не должен знать ничего о ДТО, только о модели, и ничего не знать о других сущностях

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemStorage itemStorage;
требуется еще создать сервис и использовать его, нежели сторадж напрямую

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +                if (item.getDescription().toLowerCase().contains(text.toLowerCase())) {
text.toLoweCase() лучше сделать единожды

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    private void duplicateValidation(User user, long userId) {
Не очень оптимально обходить список, лучше завести хэшсет с имейлами

2023-07-22 09:54 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        for (Item item : allItem.values()) {
Полный обход списка не лучший способ - лучше завести еще одну мапу, только хранить юзера на список его вещей

2023-07-22 19:33 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") long userId, @Valid @RequestBody Item item) {
исправил

2023-07-22 19:34 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @NotBlank(message = "Имя не может быть пустым!")
исправил

2023-07-22 19:34 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
исправил

2023-07-22 19:34 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private long userId;
исправил

2023-07-22 19:35 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public ItemDto createItem(long userId, Item item) {
исправил

2023-07-22 19:35 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemStorage itemStorage;
исправил

2023-07-22 19:38 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +                if (item.getDescription().toLowerCase().contains(text.toLowerCase())) {
исправил

2023-07-23 20:39 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    private void duplicateValidation(User user, long userId) {
Не очень понял идею. Если завести хэшсет, то имейлы в нем будут уникальными, как мне искать дубли? Завести в самом классе или только в методе? Если это обязательное замечание, пожалуйста, дайте пояснения

2023-07-23 20:40 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        for (Item item : allItem.values()) {
Завести в самом классе и добавлять в нее значения в момент создания предмета? Если это обязательное замечание, пожалуйста, дайте пояснения

2023-07-24 12:39 UTC, alexache approved these changes

2023-07-24 12:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final InMemoryItemStorage inMemoryItemStorage;
Нужно полагаться на интерфейсы, а не конкретные реализации

2023-07-24 12:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        for (Item item : allItem.values()) {
Да, в самом классе параллельно с основной мапой, и да, при создании добавлять в нее. Это важно с точки зрения производительности, но не очень критично с точки зрения того, что будет переписано в следующем спринте

2023-07-24 12:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private final InMemoryUserStorage inMemoryUserStorage;
И тут комментарий про интерфейс вместо реализации

2023-07-24 12:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    private void duplicateValidation(User user, long userId) {
В классе. Имейлы будут уникальными + можно при добавлении/обновлении пользователя проверять, нет ли этого имела в сете

2023-07-28 14:47 UTC, merged