ТЗ14. Переход на базу данных. Добавлен новый функционал
VladislavKubarev/java-shareit pull request #2
Opened 2023-08-08 09:15 UTC by VladislavKubarev

2023-08-08 21:28 UTC, alexache requested changes

2023-08-08 21:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        return getClass().hashCode();
В данном методе тоже лучше полагаться только на id, как и в методе выше

2023-08-08 21:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(" select i from Item i " +
Такой запрос тоже реалистично сделать через имя метода с помощью equalsIgnoreCase

2023-08-08 21:28 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemWithBookingAndCommentsDto.setNextBooking(getNextBooking(item.getId()));
В каждой из этих 3 строчек запросы к базе, а все это внутри мап метода по списку вещей, то есть это запросы к базе внутри цикла, что нельзя делать

2023-08-09 17:29 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(" select i from Item i " +
оставил как было дано в примере, надеюсь вы не против

2023-08-09 17:29 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        return getClass().hashCode();
не уверен, правильно ли переопределил

2023-08-09 17:30 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            itemWithBookingAndCommentsDto.setNextBooking(getNextBooking(item.getId()));
не уверен

2023-08-09 18:06 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +    @Query(" select i from Item i " +
Будет сложнее в следующем спринте

2023-08-09 18:11 UTC, alexache requested changes

2023-08-09 18:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        return Objects.hash(getId());
Метод getId необязателен, можно ведь напрямую к полю обращаться внутри класса, а в остальном - ок

2023-08-09 18:11 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRepository.findByOwnerId(userId).stream().map(item -> findItemById(item.getId(), userId))
Тут суть не поменялась - есть запрос к базе в цикле, так очень неоптимально делать. Нужно сделать несколько запросов - получение всех бронирований вещей юзера, получение всех комментарий по списку вещей

2023-08-10 11:50 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +        return Objects.hash(getId());
исправлено

2023-08-10 11:55 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRepository.findByOwnerId(userId).stream().map(item -> findItemById(item.getId(), userId))
исправил, но подскажите, пожалуйста, как это можно сделать красивее и компактнее

2023-08-10 20:33 UTC, alexache approved these changes

2023-08-10 20:33 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +
Запросов к базе в цикле нет, и это хорошо, но ты прав, что это можно сделать ещё немного оптимальнее.
Как предварительный шаг после получения данных из базы можно разложить комментарии и бронирования в мапы айди вещи на списки комментариев/бронирований с помощью стрима, коллектора с groupingBy

2023-08-13 11:12 UTC, merged