ТЗ15. Добавлен запрос вещи, добавлены тесты.
VladislavKubarev/java-shareit pull request #3
Opened 2023-08-27 00:38 UTC by VladislavKubarev

2023-08-28 06:25 UTC, alexache requested changes
Немного еще не хватает тестов - интеграционного хотя бы одного на несколько тест кейсов, и можно еще немного @JsonTest на ДТО

2023-08-28 06:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static BookingResponseDto toBookingDto(Booking booking) {
Если все методы мапперы статичны (что вполне допустимо), то зачем аннотация @Component на классе?

2023-08-28 06:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Generated
Для чего эта аннотация? Мне кажется лишней

2023-08-28 06:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Booking> bookingList = bookingRepository.findByItemOwnerIdOrderByStartDesc(userId, pageable);
Не уверен, что pageable применим уже и к этому набору данных, он подразумевается к списку вещей, бронирований может быть больше, нужно получать вместо этого бронирования тех вещей, которые получены строчкой выше

2023-08-28 06:25 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +                .andExpect(jsonPath("$.id").value(bookingResponseDto.getId()));
Лучше проверять большее количество пропертей, не только айди

2023-08-28 06:25 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTests.java
> +    BookingRepository bookingRepository;
Модификаторы доступа у полей чаще принято указывать (даже в тестах)

2023-08-28 10:59 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +    public static BookingResponseDto toBookingDto(Booking booking) {
+

2023-08-28 11:01 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Generated
c помощью этой аннотации над переопределением equals и hashCode удалось увеличить процент покрытия тестами

2023-08-28 16:45 UTC, VladislavKubarev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        List<Booking> bookingList = bookingRepository.findByItemOwnerIdOrderByStartDesc(userId, pageable);
+

2023-08-28 16:49 UTC, VladislavKubarev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTests.java
> +    BookingRepository bookingRepository;
+

2023-08-28 18:26 UTC, VladislavKubarev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +                .andExpect(jsonPath("$.id").value(bookingResponseDto.getId()));
+

2023-08-29 19:23 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Generated
Я бы сказал, это неуместным хаком. Эта аннотация для автоматически сгенерированного кода, которым данный метод по факту не является. Покрытие в таком случае легко получить за счет использования equals метода в тестах, иначе зачем вообще эти 2 метода определять, если они не нужны

2023-08-29 19:27 UTC, alexache approved these changes

2023-08-29 19:27 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingIntegrationTests.java
> +    private BookingServiceImpl bookingServiceImpl;
Интерфейс, не реализация нужна здесь

2023-08-30 08:23 UTC, merged