ТЗ16. Контейнеризация. Первая проверка
VladislavKubarev/java-shareit pull request #4
Opened 2023-08-31 18:29 UTC by VladislavKubarev

2023-09-01 05:17 UTC, alexache requested changes
В дополнение: для чего удалены тесты?

2023-09-01 05:17 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of(
Мапа из одного элемента не обязательна, можно обойтись без нее

2023-09-01 05:17 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingClient.createBooking(userId, bookingDto);
Хорошо бы добавить логгирование в методы контроллеров

2023-09-01 05:17 UTC, alexache commented on pom.xml
>  	<dependencies>
В родительском модуле не должно быть зависимостей через dependency, можно настраивать нужные версии через dependencyManagement, иначе оба модуле получат общие зависимости

2023-09-01 05:17 UTC, alexache commented on pom.xml
>  	<dependencies>
В частности, у модуля сервиса не должно быть зависимости от валидаций

2023-09-01 05:17 UTC, alexache commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
>                                       @RequestParam(required = false, defaultValue = "0") @Min(0) int from,
Валидаций не должно оставаться

2023-09-01 10:27 UTC, VladislavKubarev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of(
+

2023-09-01 10:36 UTC, VladislavKubarev commented on pom.xml
>  	<dependencies>
+

2023-09-01 10:40 UTC, VladislavKubarev commented on server/src/main/java/ru/practicum/shareit/item/ItemController.java
>                                       @RequestParam(required = false, defaultValue = "0") @Min(0) int from,
+

2023-09-01 11:09 UTC, VladislavKubarev commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        return bookingClient.createBooking(userId, bookingDto);
+

2023-09-02 11:15 UTC, alexache approved these changes

2023-09-03 18:40 UTC, merged